### ISSUE TITLE
Profilers

### ISSUE THREAD

**Issue by axeII** [Hnatekmar/GeneticAlgorithm#11]
Few tips for profiles to check speed of program speed specified for d.
https://github.com/andralex/phobos/blob/benchmark/std/benchmark.d
https://github.com/jmcabo/avgtime
http://dlang.org/phobos/std_datetime.html#benchmark
https://stackoverflow.com/questions/17856567/measuring-execution-time-in-the-d-language

**Comment by kysel** [comment]
#15

**Comment by Hnatekmar** [comment]
https://github.com/Hnatekmar/GeneticAlgorithm/pull/24 To uzavírá
