### ISSUE TITLE
opt.d is literally useless

### ISSUE THREAD

**Issue by zdenek-biberle** [Hnatekmar/GeneticAlgorithm#17]
`getoptions` is badly named and it does not even return anything.

**Comment by kysel** [comment]
Ayyyyy

**Comment by axeII** [comment]
Fixed in becd9a0.

**Comment by axeII** [comment]
@Hnatekmar review, close issue.

**Comment by axeII** [comment]
Edited here c83d847.

**Comment by Hnatekmar** [comment]
As it stands the code isn't robust enough. We need to check if user specifies values in correct range etc... For example in this version user could specify values that are not valid (negative number of epochs, ...).
Also that commit does not pass trough travis because it does not conform to https://github.com/Hnatekmar/GeneticAlgorithm/blob/master/.editorconfig You should probably use https://github.com/editorconfig/editorconfig-vim to remedy that ;)
Overall I think this code is on right path but it needs some changes before we can use it. See my comments and if you have any questions feel free to ask me.

**Comment by zdenek-biberle** [comment]
BTW @L3rchal, proč to děláš v branchi "rectangle" a ne v...idk, třeba branchi "options"?

Taky navrhuju z toho udělat PR, tam se líp reviewuje a takový věci.

**Comment by Hnatekmar** [comment]
Jo asi přejdeme na to, že každej budeme mít jednu branchi a do ní budeme commitovat (stejně neřešíš víc, jak 1 issue...)

**Comment by zdenek-biberle** [comment]
Ne, budeš mít jednu branchi na jednu změnu, protože to dává mnohem větší smysl a je to maintainovatelnější.

Branch "rectangle" dává smysl, ale parsování optionů v ní nemá co dělat.

**Comment by Hnatekmar** [comment]
Ale trochu nepřehledný

**Comment by zdenek-biberle** [comment]
Ne? Jak je nepřehledný to, že v branchi "rectangle" se dělá kreslení obdélníků, v branchi "options" se dělá parsování optionů, v branchi "whateverthefuck" se dělá whateverthefuck atd.

Takhle akorát získáš přehlednost, protože se zabýváš tím, na čem se dělá, a ne tím, kdo na tom dělá.

Nehledě na to, že do jedný branche může přispívat více lidí a jeden člověk může mít rozpracováno několik věcí (v různých branchích) zároveň. Něco takového je zcela nerealizovatelné v situaci, kdy máš branchi na člověka a konec.

**Comment by axeII** [comment]
Tak protoze tohle neni webdev tak muzu jmenovat branche jak chci.

**Comment by axeII** [comment]
Priste pojmenuji **thisfuckingawesomebranch**

**Comment by Hnatekmar** [comment]
Což v tomto projektu zas tak nevadí, protože každý dělá na své separátní issue ale chápu, že ve větších projektech to může být problém...

**Comment by zdenek-biberle** [comment]
1. Dobrej label
1. Přešel jsi můj druhej point - jeden člověk může mít víc rozpracovaných věcí zároveň, tj. něco udělám, pushnu to, udělám PRko, začnu pracovat na něčem jiným, v tom PRku se najdou bugy, takže stopnu to, co dělám, a chci se vrátit k tomu PRku, ale už jsem něco commitnul dalšího a tak je to celý vopruz (nehledě na to, že to _nemůžu pushnout_, protože by se to přidalo do toho udělanýho PRka).

   V takovým případě stejně skončíš u branchování, protože máš nějakej commit, kterej měl být poslední v tom PRku, ale ty teď nad něj musíš postavit novej, opravnej commit, ale to nejde, protože už jsi tam dal zcela unrelated commit. Takže co uděláš? Branchneš do nové branche, resetneš ty unrelated commity, opravíš, commitneš, pushneš. No a pak? Uh, můžeš mergnout tu branchnutou branchu zpátky, ale to je totálně dementní a useless (jak jsem říkal, nemůžeš pak pushovat, protože nad tou branchou máš PRko), takže pokračuješ v práci v té nové branchi. A to je to, co jsi měl dělat od začátku.

**Comment by Hnatekmar** [comment]
1. Ten label je super 😄 
2. Point

**Comment by axeII** [comment]
Dobrej label +1
