### ISSUE TITLE
Testing genetic algorithm

### ISSUE THREAD

**Issue by Hnatekmar** [Hnatekmar/GeneticAlgorithm#2]
We should write few test programs for library and see how it performs on real tasks such as curve fitting see: http://subprotocol.com/system/genetic-js.html If it performs poorly we will have to make changes to GA You may also look at https://github.com/jenetics/jenetics and https://github.com/jburguete/genetic for inspiration

**Comment by Hnatekmar** [comment]
I think we can close this issue with c965bc58c522ae61ed601b2a76f3ad795e4ce62b. What do you think @L3rchal ?

**Comment by axeII** [comment]
Yes we can. Closing this issue.

**Comment by zdenek-biberle** [comment]
>We should write few test programs

Proč byste jich psali málo?

>What do you think @L3rchal ?

Mezera před otazníkem!!!!!1!!1!1!!1!11!!eleven

**Comment by Hnatekmar** [comment]
Protože si ten graf necháme vykreslit jenom u věcí u kterých použijeme paralelní programování

**Comment by Hnatekmar** [comment]
Tak, protože jích hodně není potřeba 😄
