### ISSUE TITLE
Rasterizer rewrite

### ISSUE THREAD

**Issue by Hnatekmar** [Hnatekmar/GeneticAlgorithm#21]
Rewrite rasterizer so that it draws some other shape like rectangle and try if it helps GA.

**Comment by axeII** [comment]
Done in this branch/commit ... rectangle / 028b9fb
Also I also added check for input file.

**Comment by Hnatekmar** [comment]
Maybe error messages could be improved (see my comment) but otherwise LGTM 👍

**Comment by axeII** [comment]
Ok small edit here c3e4859.

**Comment by Hnatekmar** [comment]
👍 closing issue for now. But we should really decide whether we want user input be in Czech. For now it is inconsistent for example some of my assertions are in Czech...
