### ISSUE TITLE
Refaktorování

### ISSUE THREAD

**Issue by Hnatekmar** [Hnatekmar/GeneticAlgorithm#29]
Je potřeba zase udělat menší úklid předtím než to všechno spojíme dohromady. Jedná se především o rozdělení fitness funkce na vykreslovací část a samotnou fitness funkci a možná pár dalších úprav (přechod na dstyle atd...)

**Comment by zdenek-biberle** [comment]
A co takhle VÍC RŮZNÝCH RASTERIZÉRŮ! YAY!

**Comment by Hnatekmar** [comment]
taky mě napadlo, že by to mohlo střídat mezi kruhy a obdelníky ale možná by to nevypadalo hezky...

**Comment by zdenek-biberle** [comment]
Tam je to pak trochu nic moc, protože popisy kruhů a obdélníků zabírají odlišný počet bitů v genomu.

**Comment by Hnatekmar** [comment]
to taky

**Comment by Hnatekmar** [comment]
navíc současný progress vypadá dobře... Obdelníky jsou super 😄
